config/routes.rb
Wishping::Application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"} 

  get "home/index"

  match 'users/:id/add_amazon_item' => 'users#add_amazon_item'
  match 'users/:id/update_prices' => 'users#update_prices', :as => :update_prices

  resources :items

  resources :users do
    match 'items/add_amazon_item' => 'items#add_amazon_item'
    resources :items
  end

  root :to => "home#index"

end

app/models/item.rb
class Item < ActiveRecord::Base

  require 'time'
  require 'uri'
	require 'openssl'
  require 'base64'
  include HTTParty

	belongs_to :user
  has_many :prices

  default_scope order("created_at DESC")
	
	# Search Amazon based on specific search index and keywords
  # See http://docs.amazonwebservices.com/AWSECommerceService/latest/DG/ItemSearch.html
  def self.amazon_item_search(search_index, keywords)
    # Escape the keywords, replacing spaces with plus signs
    escaped_keywords = CGI.escape(keywords)
    url_params = {
      'AssociateTag' => S3[:tag],
      'AWSAccessKeyId' => S3[:key],
      'Keywords' => escaped_keywords,
      'Operation' => 'ItemSearch',
      'SearchIndex' => search_index,
      'Service' => 'AWSECommerceService',
      'Timestamp' => Time.now.utc.iso8601,    # TIME HAS TO BE IN ISO8601 or signature won't match
      'Version' => '2011-08-01'
    }
    canonical_querystring = create_canonical_querystring(url_params)
    encoded_signature = encode_signature(canonical_querystring) 
    url_params['Signature'] = escaped_signature
    # UNESCAPE the keywords (this took me forever to figure out, and there's probably a better way to do it)
    url_params['Keywords'] = url_params['Keywords'].gsub(/%20/,'+')
    querystring = create_querystring(url_params)
    puts "#{ENV['AWS_URL']}?#{querystring}"
	end


  # Retrieve an item's information using its ASIN and response group
  # More on Amazon's response groups here: http://docs.amazonwebservices.com/AWSECommerceService/latest/DG/ItemLookup.html
  def self.amazon_item_lookup(asin, response_group)
    url_params = {
      'AssociateTag' => S3[:tag],
      'AWSAccessKeyId' => S3[:key],
      'Operation' => 'ItemLookup',
      'ItemId' => asin,
      'ResponseGroup' => response_group,
      'Service' => 'AWSECommerceService',
      'Timestamp' => Time.now.utc.iso8601,    # TIME HAS TO BE IN ISO8601 or signature won't match
      'Version' => '2011-08-01'
    }
    canonical_querystring = create_canonical_querystring(url_params)
    encoded_signature = encode_signature(canonical_querystring)
    url_params['Signature'] = encoded_signature
    querystring = create_querystring(url_params)
    get("#{ENV['AWS_URL']}?#{querystring}")
    # puts `curl -X"GET" "#{amazon_endpoint}?#{querystring}" -A"simple ruby aws sdb wrapper"`
    # puts xmlreturn
    # puts "#{amazon_endpoint}?#{querystring}"
  end


  # Returns a hash with keys "item_attributes" and "amazon_price" if there are no errors,
  # or a hash with key "errors" if there are errors
  def self.get_amazon_item(asin)
    amazon_item = self.get_amazon_item_attributes(asin)
  end


  # Get an Amazon item's attributes via asin;
  # - returns a string if there's an error, otherwise returns a hash of the attributes
  def self.get_amazon_item_attributes(asin)
    amazon_item_attributes = {} 
    amazon_lookup_response = self.amazon_item_lookup(asin, "ItemAttributes")
    amazon_item_attributes["errors"] = self.amazon_lookup_error(amazon_lookup_response)
    return amazon_item_attributes if amazon_item_attributes["errors"].present?
    amazon_item_attributes["title"] = amazon_lookup_response["ItemLookupResponse"]["Items"]["Item"]["ItemAttributes"]["Title"]
    amazon_item_attributes["list_price"] = amazon_lookup_response["ItemLookupResponse"]["Items"]["Item"]["ItemAttributes"]["ListPrice"]["Amount"].to_f / 100
    amazon_item_attributes["asin"] = asin
    price = self.get_amazon_item_price(asin)
    if price.kind_of?(Float)
      amazon_item_attributes["amazon_price"] = price
    else
      amazon_item_attributes["errors"] = price
    end
    amazon_item_attributes
  end

  # # get_amazon_item_attributes returns a hash like this:
  # {
  #   "Binding"=>"Lawn & Patio", 
  #   "Brand"=>"Weber", 
  #   "CatalogNumberList"=>
  #     {"CatalogNumberListElement"=>"1421001"}, 
  #   "Color"=>"Black", 
  #   "Department"=>"Garden & Outdoor", 
  #   "EAN"=>"0077924002205", 
  #   "EANList"=>
  #     {"EANListElement"=>"0077924002205"}, 
  #   "Feature"=>
  #     ["The Weber Performer charcoal grill features a  Touch-N-Go gas-ignition system", 
  #       "It has a total cooking are of 363 square-inches", 
  #       "It comes with a rolling steel-frame cart, work table;,3 tool hooks, and a lid-mounted thermometer", 
  #       "Also included are 2 charcoal fuel holders, and a charcoal storage container", 
  #       "Measures 28-1/2-by-50-1/4-by-40 inches"], 
  #   "ItemDimensions"=>
  #     {
  #       "Height"=>"4000", 
  #       "Length"=>"2850", 
  #       "Weight"=>"13700", 
  #       "Width"=>"5025"
  #     }, 
  #   "Label"=>"Weber", 
  #   "ListPrice"=>
  #     {
  #       "Amount"=>"42900", 
  #       "CurrencyCode"=>"USD", 
  #       "FormattedPrice"=>"$429.00"
  #     }, 
  #   "Manufacturer"=>"Weber", 
  #   "Model"=>"1421001", 
  #   "MPN"=>"1421001", 
  #   "NumberOfItems"=>"1", 
  #   "PackageDimensions"=>
  #     {
  #       "Height"=>"2000", 
  #       "Length"=>"3900", 
  #       "Weight"=>"9600", 
  #       "Width"=>"2850"
  #     }, 
  #   "PackageQuantity"=>"1", 
  #   "PartNumber"=>"1421001", 
  #   "ProductGroup"=>"Lawn & Patio", 
  #   "ProductTypeName"=>"OUTDOOR_LIVING", 
  #   "Publisher"=>"Weber", 
  #   "SKU"=>"1421001", 
  #   "Studio"=>"Weber", 
  #   "Title"=>"Weber 1421001 Performer Charcoal Grill, Black", 
  #   "UPC"=>"077924002205", 
  #   "UPCList"=>
  #     {"UPCListElement"=>"077924002205"}, 
  #   "Warranty"=>"2-year limited warranty"
  # } 


  # Get an Amazon item's attributes via asin;
  # - returns a string if there's an error, otherwise returns the price as a boolean in dollars
  def self.get_amazon_item_price(asin)
    amazon_lookup_response = self.amazon_item_lookup(asin, "Offers")
    amazon_error = amazon_lookup_error(amazon_lookup_response)
    return amazon_error if amazon_error.present?
    amazon_item_price = amazon_lookup_response["ItemLookupResponse"]["Items"]["Item"]["Offers"]["Offer"]["OfferListing"]["Price"]["Amount"].to_f / 100
  end


  def self.amazon_lookup_error(response)
    if response["ItemLookupResponse"]["Items"]["Request"]["Errors"].present?
      response["ItemLookupResponse"]["Items"]["Request"]["Errors"]["Error"]["Message"]
    end
  end




  def update_prices
    new_current_price = Item.get_amazon_item_price(self.asin)
    if new_current_price.kind_of?(Float)  # If it's not a float, it's an error
      self.prices.create(:amount => new_current_price)
      # If the current price has changed, update the current, high and low prices as needed
      if self.current_price != new_current_price
        self.current_price = new_current_price
        self.highest_price = new_current_price if new_current_price > self.highest_price
        self.lowest_price = new_current_price if new_current_price < self.lowest_price
      end
      self.price_updated_at = Time.now
      self.save!
    else
      puts new_current_price
    end
    
  end


  private

  def self.create_canonical_querystring(params)
    # Create the querystring, making sure to escape to remove colons and commas.  
    # Use gsub to make sure the proper space character is used
    params.sort.collect { |key, value| [CGI.escape(key.to_s), CGI.escape(value.to_s).gsub(/%2B/, '%20')].join('=') }.join('&')
  end


  def self.create_querystring(params)
    # Create the querystring with the new params.  DON'T escape the params this time
    params.collect { |key, value| [key, value].join('=') }.join('&') 
  end


  def self.encode_signature(canonical_querystring)
    # Append the querystring to the proper amazon header
    # Don't tab the string_to_sign over!  Signature won't encode properly!  Screw your pretty margins!
    string_to_sign = 
"GET
webservices.amazon.com
/onca/xml
#{canonical_querystring}"
    digest = OpenSSL::Digest.new("sha256")
    hmac = OpenSSL::HMAC.digest(digest, S3[:secret], string_to_sign)
    signature = Base64.encode64(hmac).chomp
    # Escape the plus (+) and equal (=) characters in the signature
    # Make sure to use chomp, since this adds a newline at the end
    escaped_signature = URI.escape(signature, "+=/")
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_filter :authenticate_user!   # Devise authentication

  # load_and_authorize_resource :user
  # load_and_authorize_resource :through => :user         # Cancan authorization
  # skip_authorize_resource :only => :show
  # skip_authorize_resource :user, :only => :show

  def index
    @items = Item.find_all_by_user_id(params[:user_id])
    @amazon_item = Item.get_amazon_item(params[:item][:asin]) if params[:item]
      
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @items }
    end
  end


  def show
    @item = Item.find(params[:id])
    @price_array = []
    @item.prices.each {|price| @price_array << price.amount }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end


  def edit
    @item = Item.find(params[:id])
  end


  def create
    @item = current_user.items.create()
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.' 
    else
      render :new
    end
  end


  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(params[:item])
      redirect_to user_items_path, :notice => "Item Added!"
    else
      render :edit
    end
  end


  def destroy
    @user = User.find(params[:user_id])
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to user_path(@user)
  end


end

app/helpers/items_helper.rb
module ItemsHelper

	def row_class(item)
		if item.highest_price > 0 and item.lowest_price > 0 and item.highest_price != item.lowest_price
			if item.current_price >= item.highest_price
				"highest-price"
			elsif item.current_price <= item.lowest_price
				"lowest-price"
			end
		end
	end


	def amazon_link(asin)
		"http://www.amazon.com/gp/product/#{asin}?tag=#{S3[:tag]}"
	end
	
end

app/views/items/_amazon_search_form.html.erb
<%= form_for :item, :html => {:method => :get}  do |f| %>
    <p>
        <%= f.label :asin, "Amazon ASIN" %>: <%= f.text_field :asin, :size => 10 %> 
        <%= f.submit "Look up item" %>
    </p>
<% end %>

<% if amz_item.present? %>
    <% if amz_item["errors"].present? %>
        <div class = "amazon_error">
            <%= amz_item["errors"] %>
        </div>
    <% else %>
        <%= form_for :amazon_item, :url => { :controller => 'users', :action => 'add_amazon_item', :name => amz_item["title"], :price => amz_item["amazon_price"], :asin => amz_item["asin"]} do |add_form| %>
            <p>
                <strong>Item:</strong> <%= amz_item["title"] %><br />
                <strong>List Price:</strong> <%= number_to_currency(amz_item["list_price"]) %><br />
                <strong>Current Lowest New Price:</strong> <%= number_to_currency(amz_item["amazon_price"]) %>
            </p>
            <%= add_form.submit "Add to My Items" %>
        <% end %>
    <% end %>
<% end %>
<br />
<br />

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :seller %><br />
    <%= f.text_field :seller %>
  </div>
  <div class="field">
    <%= f.label :lowest_price %><br />
    <%= f.text_field :lowest_price %>
  </div>
  <div class="field">
    <%= f.label :highest_price %><br />
    <%= f.text_field :highest_price %>
  </div>
  <div class="field">
    <%= f.label :current_price %><br />
    <%= f.text_field :current_price %>
  </div>
  <div class="field">
    <%= f.label :price_updated_at %><br />
    <%= f.datetime_select :price_updated_at %>
  </div>
  <div class="field">
    <%= f.label :asin %><br />
    <%= f.text_field :asin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_my_items_list.html.erb
<% if @items.present? %>
    <h2>My Items</h2>
    <p>
        <%= button_to "Get the current Amazon price", update_prices_path(@user) %>
    </p>
    <table id = "my-item-list" >
        <tbody>
            <tr>
                <th>
                    Item
                </th>
                <th>
                    Current Price
                </th>
                <th>
                    Last Updated
                </th>
                <th>
                    Highest Price
                </th>
                <th>
                    Lowest Price
                </th>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
            </tr>
            <% @items.each do |item| %>
                <tr class="<%= "#{cycle('list-line-odd', 'list-line-even')} #{row_class(item)}" %>" >
                    <td>
                        <%= link_to item.name, item_path(item) %>
                    </td>
                    <td>
                        <%= number_to_currency(item.current_price) %>
                    </td>
                    <td>
                        <%= item.price_updated_at.to_formatted_s(:long) %>
                    </td>
                    <td class = "highest-price">
                        <%= number_to_currency(item.highest_price) %>
                    </td>
                    <td class = "lowest-price">
                        <%= number_to_currency(item.lowest_price) %>
                    </td>
                    <td>
                        <%= link_to image_tag("/assets/buy_amazon.gif"), amazon_link(item.asin) %>
                    </td>
                    <td>
                        <%= button_to "Remove", user_item_path(@user, item), confirm: "Are you sure you want to remove #{item.name} from your list?", method: :delete%>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <p>
        You haven't added any Amazon items to your list. 
    </p>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<%= form_for :item, :html => {:method => :get}  do |f| %>
    <p>
        <%= f.label :asin, "Amazon ASIN" %>: <%= f.text_field :asin, :size => 10 %> 
        <%= f.submit "Look up item" %>
    </p>
<% end %>

<% if @amazon_items.present? && !@amazon_error.present? %>
    <% @amazon_items.each do |amazon_item| %>
        <%= form_for :amazon_item, :url => { :controller => 'items', :action => 'add_amazon_item', :name => amazon_item[1]["Items"]["Item"]["ItemAttributes"]["Title"], :price => amazon_item[1]["Items"]["Item"]["OfferSummary"]["LowestNewPrice"]["Amount"], :asin => amazon_item[1]["Items"]["Request"]["ItemLookupRequest"]["ItemId"]} do |add_form| %>
            <p>
                <strong>Item:</strong> <%= amazon_item[1]["Items"]["Item"]["ItemAttributes"]["Title"] %><br />
                <strong>List Price:</strong> <%= amazon_item[1]["Items"]["Item"]["ItemAttributes"]["ListPrice"]["FormattedPrice"] %><br />
                <strong>Current Lowest New Price:</strong> <%= amazon_item[1]["Items"]["Item"]["OfferSummary"]["LowestNewPrice"]["FormattedPrice"] %>
            </p>
            <%= add_form.submit "Add to My Items" %>
        <% end %>
    <% end %>
<% elsif @amazon_error.present? %>
    <div class = "amazon_error">
        <%= @amazon_error %>
    </div>
<% end %>
<br />
<br />

<% if @items.present? %>
    <h2>My Items</h2>
    <table id = "my-item-list" >
        <tbody>
            <tr>
                <th>
                    Item
                </th>
                <th>
                    Current Price
                </th>
                <th>
                    Last Updated
                </th>
                <th>
                    Highest Price
                </th>
                <th>
                    Lowest Price
                </th>
            </tr>
            <% @items.each do |item| %>
                <tr class="<%= "#{cycle('list-line-odd', 'list-line-even')} #{row_class(item)}" %>" >
                    <td>
                        <%= item.name %>
                    </td>
                    <td>
                        <%= number_to_currency(item.current_price) %>
                    </td>
                    <td>
                        <%= item.price_updated_at.to_formatted_s(:long) %>
                    </td>
                    <td class = "highest-price">
                        <%= number_to_currency(item.highest_price) %>
                    </td>
                    <td class = "lowest-price">
                        <%= number_to_currency(item.lowest_price) %>
                    </td>
                    <td>
                        <%= button_to "Remove", user_item_path(current_user, item), confirm: "Are you sure you want to remove #{item.name} from your list?", method: :delete%>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <p>
        You haven't added any Amazon items to your list. 
    </p>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Lowest price:</b>
  <%= @item.lowest_price %>
</p>

<p>
  <b>Highest price:</b>
  <%= @item.highest_price %>
</p>

<p>
  <b>Current price:</b>
  <%= @item.current_price %>
</p>

<p>
  <b>Price updated at:</b>
  <%= @item.price_updated_at %>
</p>

<p>
  <b>Asin:</b>
  <%= @item.asin %>
</p>
<p>
  <%= image_tag(Gchart.line(:data => @price_array)) %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>